name: Java CI  # Workflow name

on:
  push:
    branches:
      - Weixian  
  pull_request:
    branches:
      - Weixian

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v3  

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  
          distribution: 'temurin'  

      - name: Compile Java Code
        run: |
          ls -R  # 
          cd HolidayTravelVehicles/HolidayTravelVehicles  # 进入你的 Java 代码目录
          javac -d . *.java  # 编译所有 Java 文件

      - name: Run Java Application
        run: |
          cd HolidayTravelVehicles/HolidayTravelVehicles  # 进入 Java 代码目录
          java Main  # 运行 Main.java
